#pragma once

//Event Tracker Library Version
#define MAJOR_VERSION 1
#define MINOR_VERSION 0
#define PATCH_VERSION 0
#define EVENT_TRACKER_VERSION TOSTRING(MAJOR_VERSION) "." TOSTRING(MINOR_VERSION) "." TOSTRING(PATCH_VERSION)